fix(deb): allow fails via test deb install in docker

diff --git a/.github/actions/tests/install/deb/action.yml b/.github/actions/tests/install/deb/action.yml
--- a/.github/actions/tests/install/deb/action.yml
+++ b/.github/actions/tests/install/deb/action.yml
@@ -45,8 +45,9 @@ runs:
         VERIFY_COMMANDS: ${{ inputs.verify_commands }}
       run: |
         set -eux
+        mkdir summary
         curl -fsSL ${GREENGAGE_REPO_URL}/repositories/gpg \
-          | sudo gpg --dearmor -o /etc/apt/keyrings/greengagedb.gpg
+          | sudo gpg --dearmor -o /etc/apt/keyrings/greengagedb.gpg || (echo "Error: ${GREENGAGE_REPO_URL} GPG installation" > summary/error.log ; exit 1)
 
         docker run --rm \
           -v "$(pwd)/deb-packages:/deb-packages" \
@@ -70,10 +71,10 @@ runs:
                 > /etc/apt/sources.list.d/greengagedb.list
             fi
 
-            eval "$PRE_INSTALL_COMMANDS"
+            eval "$PRE_INSTALL_COMMANDS" || (echo "Error: pre-insatll commands: '${PRE_INSTALL_COMMANDS}' execution" >> /summary/error.log ; exit 1)
             apt-get update -q
-            apt-get install -y /deb-packages/*.deb
-            eval "$VERIFY_COMMANDS"
+            apt-get install -y /deb-packages/*.deb  || (echo "Error: 'apt-get install -y /deb-packages/*.deb' execution" >> /summary/error.log ; exit 1)
+            eval "$VERIFY_COMMANDS" || (echo "Error: verify commands: '${VERIFY_COMMANDS}' execution" >> /summary/error.log ; exit 1)
 
             for deb in /deb-packages/*.deb; do
               pkg=$(dpkg-deb -f "$deb" Package)
@@ -81,6 +82,8 @@ runs:
                 || echo "Status: not-installed" > /summary/${pkg}.txt
             done
           '
+
+          echo "No errors" > summary/error.log
 
     - name: Upload summary artifacts
       id: upload-summary
