upd(.github/workflows/greengage-reusable-upload.yml): Delete GHCR tags except latest

diff --git a/.github/workflows/greengage-reusable-upload.yml b/.github/workflows/greengage-reusable-upload.yml
--- a/.github/workflows/greengage-reusable-upload.yml
+++ b/.github/workflows/greengage-reusable-upload.yml
@@ -88,13 +88,14 @@ jobs:
 
       - name: Tag and push Docker image
         env:
+          REF: ${{ github.ref }}
           IMAGE: ggdb${{ inputs.version }}_${{ inputs.target_os }}${{ inputs.target_os_version }}
         run: |
           GHCR_IMAGE=ghcr.io/${{ github.repository }}/${IMAGE}       ; export GHCR_IMAGE=${GHCR_IMAGE,,}
           DOCKERHUB_IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/${IMAGE} ; export DOCKERHUB_IMAGE=${DOCKERHUB_IMAGE,,}
 
           # For tagged pushes, tag with git tag and check if it's the latest semantic tag
-          if [[ "${{ github.ref }}" =~ ^refs/tags/ ]]; then
+          if [[ "$REF" =~ ^refs/tags/ ]]; then
             # All HEAD ref tags
             SEMANTIC_TAGS=$(git tag --merged | grep -E "^${{ inputs.version }}\.[0-9]+\.[0-9]+$" | sort -V)
             # Get the latest semantic tag
@@ -122,3 +123,22 @@ jobs:
 
           # If tag is really latest or testing
           [ -n "$LATEST" ] && docker tag $GHCR_IMAGE:${{ github.sha }} $DOCKERHUB_IMAGE:$LATEST && docker push $DOCKERHUB_IMAGE:$LATEST || true
+
+      - name: Delete GHCR tags except latest
+        if: github.event_name == 'push'
+        env:
+          IMAGE: ggdb${{ inputs.version }}_${{ inputs.target_os }}${{ inputs.target_os_version }}
+        run: |
+          tags=$(gh api repos/${{ github.repository }}/packages/container/${IMAGE}/versions -H "Accept: application/vnd.github+json" | jq -r '.[].metadata.container.tags[] | select(. != "latest")' || true)
+          if [ -z "$tags" ]; then
+            echo "No tags found for ${IMAGE} (excluding latest) or failed to fetch tags. Skipping deletion."
+            exit 0
+          fi
+          for tag in $tags; do
+            version_id=$(gh api repos/${{ github.repository }}/packages/container/${IMAGE}/versions -H "Accept: application/vnd.github+json" | jq -r --arg tag "$tag" '.[] | select(.metadata.container.tags[] == $tag) | .id' || true)
+            if [ -n "$version_id" ]; then
+              gh api repos/${{ github.repository }}/packages/container/${IMAGE}/versions/$version_id -X DELETE || echo "Failed to delete tag $tag (version $version_id). Continuing."
+            else
+              echo "Version ID for tag $tag not found. Skipping."
+            fi
+          done
