Update Fetch SQL dump step

diff --git a/.github/workflows/greengage-reusable-tests-behave.yml b/.github/workflows/greengage-reusable-tests-behave.yml
--- a/.github/workflows/greengage-reusable-tests-behave.yml
+++ b/.github/workflows/greengage-reusable-tests-behave.yml
@@ -84,20 +84,47 @@ jobs:
       - name: Set up Docker Compose
         uses: docker/setup-compose-action@v1
 
+      # - name: Fetch SQL dump for ${{ matrix.feature }}
+      #   if: matrix.feature == 'gpexpand'
+      #   env:
+      #     GH_TOKEN: ${{ github.token }}
+      #   run: |
+      #     sqldump_run_id=$(gh run list --workflow "Greengage SQL Dump" \
+      #       --limit 100 \
+      #       --json conclusion,headBranch,status,databaseId \
+      #       --jq 'map(select(.status=="completed" and .conclusion=="success" and .headBranch=="${{ inputs.version == '7' && '7.x' || 'main' }}")) | .[0].databaseId')
+      #     [[ "$sqldump_run_id" =~ ^[0-9]+$ ]] && \
+      #      gh run download $sqldump_run_id --name sqldump_ggdb${{ inputs.version }}_${{ inputs.target_os }}${{ inputs.target_os_version }} \
+      #      || exit 1
+      #     tar -xf ${{ inputs.target_os }}_postgres_sqldump.tar
+      #     rm -f ${{ inputs.target_os }}_postgres_sqldump.tar
+
       - name: Fetch SQL dump for ${{ matrix.feature }}
         if: matrix.feature == 'gpexpand'
         env:
           GH_TOKEN: ${{ github.token }}
         run: |
-          sqldump_run_id=$(gh run list --workflow "Greengage SQL Dump" \
+          artifact_name="sqldump_ggdb${{ inputs.version }}_${{ inputs.target_os }}${{ inputs.target_os_version }}"
+
+          run_ids=$(gh run list --workflow "Greengage SQL Dump" \
             --limit 100 \
-            --json conclusion,headBranch,status,databaseId \
-            --jq 'map(select(.status=="completed" and .conclusion=="success" and .headBranch=="${{ inputs.version == '7' && '7.x' || 'main' }}")) | .[0].databaseId')
-          [[ "$sqldump_run_id" =~ ^[0-9]+$ ]] && \
-           gh run download $sqldump_run_id --name sqldump_ggdb${{ inputs.version }}_${{ inputs.target_os }}${{ inputs.target_os_version }} \
-           || exit 1
-          tar -xf ${{ inputs.target_os }}_postgres_sqldump.tar
-          rm -f ${{ inputs.target_os }}_postgres_sqldump.tar
+            --json conclusion,status,databaseId \
+            --jq 'map(select(.status=="completed" and .conclusion=="success")) | .[].databaseId')
+
+          for run_id in $run_ids; do
+            if gh run download "$run_id" --name "$artifact_name" 2>/dev/null ; then
+              echo "::notice::SQL Dump $artifact_name found at $run_id finished workflow"
+              break
+            fi
+          done
+
+          if tar -xf ${{ inputs.target_os }}_postgres_sqldump.tar 2>/dev/null ; then
+            rm -f ${{ inputs.target_os }}_postgres_sqldump.tar
+            echo "::notice::SQL Dump ${{ inputs.target_os }}_postgres_sqldump.tar sucessfully unpacked and removed"
+          else
+            echo "::error::Artifact '$artifact_name' not found in any completed workflow run"
+            exit 1
+          fi
 
       - name: Run Behave feature ${{ matrix.feature }}
         # continue-on-error: true
