Full regression test logs uploads (#3)
- Update greengage-reusable-tests-regression.yml
- Update ReadMe REUSABLE-TESTS-REGRESSION.md

diff --git a/.github/workflows/greengage-reusable-tests-regression.yml b/.github/workflows/greengage-reusable-tests-regression.yml
--- a/.github/workflows/greengage-reusable-tests-regression.yml
+++ b/.github/workflows/greengage-reusable-tests-regression.yml
@@ -89,32 +89,48 @@ jobs:
       # Run Regression tests
       - name: Regression test with Optimizer ${{ matrix.optimizer }}
         env:
+          ARCH: 'x86-64'
+          LOG_NAME: '${{ matrix.optimizer }}'
+          LOG_EXTENSION: 'pg_log'
           IMAGE: ghcr.io/${{ github.repository }}/ggdb${{ inputs.version }}_${{ inputs.target_os }}${{ inputs.target_os_version }}:${{ github.sha }}
           CONT_NAME: ggdb${{ inputs.version }}_${{ inputs.target_os }}${{ inputs.target_os_version }}_optimizer_${{ matrix.optimizer}}
         run: |
           export IMAGE=${IMAGE,,}
+          cat > regression_optimizer_${{ matrix.optimizer }}.bash << EOF
+          # set -x
+          cd /home/gpadmin/
+          ssh-keygen -A
+          /usr/sbin/sshd
+          EXIT_CODE=0
+          bash gpdb_src/concourse/scripts/ic_gpdb.bash || EXIT_CODE=1
+          echo "Script gpdb_src/concourse/scripts/ic_gpdb.bash finished with \$EXIT_CODE"
+          for dir in results regression.diffs ${LOG_EXTENSION} ; do
+            find gpdb_src/src/test/ -name "$dir" -type d -exec tar -rf /logs/${LOG_NAME}_${ARCH}_$dir.tar "{}" \;
+          done
+          # echo "Debug find LOG_EXTENSION=$LOG_EXTENSION"
+          # find gpdb_src/gpAux/gpdemo/datadirs/ -name "*" -type d | tee /logs/log_dirs
+          find gpdb_src/gpAux/gpdemo/datadirs/ -name "$LOG_EXTENSION" -type d -exec tar -rf /logs/${LOG_NAME}_${ARCH}_$dir.tar "{}" \;
+          tar -cf /logs/${LOG_NAME}_${ARCH}_gpAdminLogs.tar gpAdminLogs/
+          tar -cf /logs/${LOG_NAME}_${ARCH}_gpAux.tar gpdb_src/gpAux/gpdemo/datadirs/gpAdminLogs/
+          exit \$EXIT_CODE
+          EOF
+
           # Run tests and save logs to a volume
-          docker run --name $CONT_NAME \
-            -v /tmp/regression_logs_${{ matrix.optimizer }}:/tmp/regression_logs \
-            -e TEST_OS=${{ inputs.target_os }} \
+          docker run -i --name $CONT_NAME \
+            -v /var/lib/docker/logs_${{ matrix.optimizer }}:/logs \
+            -e TEST_OS='${{ inputs.target_os }}' \
             -e MAKE_TEST_COMMAND="-k PGOPTIONS='-c optimizer=${{ matrix.optimizer == 'orca' && 'on' || 'off' }}' installcheck-world" \
             --sysctl 'kernel.sem=500 1024000 200 4096' \
             $IMAGE \
-            bash -c "set -o pipefail ; ssh-keygen -A && /usr/sbin/sshd && bash /home/gpadmin/gpdb_src/concourse/scripts/ic_gpdb.bash 2>&1 | tee /tmp/regression_logs/optimizer_${{ matrix.optimizer }}.log"
+            /bin/bash < ./regression_optimizer_${{ matrix.optimizer }}.bash
           status=$?
 
-          # Debug: exit code
-          echo "Exit code: '$status'"
+          # # Debug: exit code
+          # echo "Exit code: '$status'"
+          # echo "Logs saved to /var/lib/docker/logs_${{ matrix.optimizer }}"
+          # ls -lah /var/lib/docker/logs_${{ matrix.optimizer }}
 
-          # # Copy logs from volume
-          # mkdir -p regression_logs
-          # docker cp $CONT_NAME:/tmp/regression_logs regression_logs/${{ matrix.optimizer }}
-          # docker rm $CONT_NAME
-
-          # # Debug: List copied logs
-          # ls -lR regression_logs/
-
-          exit ${status:-1} # erro if not known
+          exit ${status:-1} # error if not known
 
       # Upload regression artifacts
       - name: Upload regression artifacts
@@ -122,6 +138,6 @@ jobs:
         uses: actions/upload-artifact@v4
         with:
           name: regression_optimizer_${{ matrix.optimizer }}
-          path: /tmp/regression_logs_${{ matrix.optimizer }}
+          path: /var/lib/docker/logs_${{ matrix.optimizer }}
           retention-days: 7
           if-no-files-found: warn  # Warning if no artifacts are found
